#!/usr/bin/env python3

import os
import sys

if sys.argv[1] != "start":
    sys.exit(0)

if os.path.exists("/var/lib/.initial-resize-done"):
    sys.exit(0)

import subprocess
import glob

# figure out the last partition
dev = "/dev/mmcblk0"
prefix = dev + "p"
parts = glob.glob(prefix + "*")
part_nums = [int(p[len(prefix):]) for p in parts]

part_num = max(part_nums)
part = prefix + str(part_num)

# resize the partition to the maximum size
# os.system("parted -s " + dev + " resizepart " + str(part_num) + " 100% Yes")
parted = subprocess.Popen(["parted", dev, "---pretend-input-tty"], stdin=subprocess.PIPE)
parted.stdin.write("""resizepart 3 100%
Yes
quit
""".encode())

# resize the filesystem
os.system("resize2fs " + part)

# touch file in /var/lib to indicate that we've resized the partition
with open("/var/lib/.initial-resize-done", "w") as f:
    f.write("")

sys.exit(0)
